name: my first Workflow;

on: push
jobs:
    
    first_job:
        runs-on: ubuntu-latest
        steps:
            name: print msg
         run: echo "my first workflow"

        name: list files
        run: 1s

